# Generated by Django 5.2.5 on 2025-12-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
